package at.derfl007.dfroads.datagen

import at.derfl007.dfroads.datagen.DFRoadsDatagen.addBlockWithItem
import at.derfl007.dfroads.registry.BlockRegistry
import at.derfl007.dfroads.registry.ItemRegistry
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider
import net.minecraft.registry.RegistryWrapper
import java.util.concurrent.CompletableFuture

class DFRoadsEnglishLangProvider(dataOutput: FabricDataOutput, wrapperLookup: CompletableFuture<RegistryWrapper.WrapperLookup>): FabricLanguageProvider(dataOutput, "en_us", wrapperLookup) {

    override fun generateTranslations(wrapperLookup: RegistryWrapper.WrapperLookup?, tb: TranslationBuilder) {
        tb.addBlockWithItem(BlockRegistry.ROAD_BLOCK, "Road")
        tb.addBlockWithItem(BlockRegistry.ROAD_SLAB_BLOCK, "Road Slab")
        tb.addBlockWithItem(BlockRegistry.ROAD_FULL_SLOPE_BLOCK, "Road Slope")
        tb.addBlockWithItem(BlockRegistry.ROAD_TOP_SLOPE_BLOCK, "Road Half Slope (Top)")
        tb.addBlockWithItem(BlockRegistry.ROAD_BOTTOM_SLOPE_BLOCK, "Road Half Slope (Bottom)")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_ROAD_BLOCK, "Concrete Road")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_ROAD_SLAB_BLOCK, "Concrete Road Slab")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_ROAD_FULL_SLOPE_BLOCK, "Concrete Road Slope")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_ROAD_TOP_SLOPE_BLOCK, "Concrete Road Half Slope (Top)")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_ROAD_BOTTOM_SLOPE_BLOCK, "Concrete Road Half Slope (Bottom)")
        tb.addBlockWithItem(BlockRegistry.ROAD_SIGN_BLOCK, "Road Sign")
        tb.addBlockWithItem(BlockRegistry.SIGN_POST_BLOCK, "Sign Post")
        tb.addBlockWithItem(BlockRegistry.TRAFFIC_LIGHT_BLOCK, "Traffic Light")
        tb.addBlockWithItem(BlockRegistry.LED_SIGN_BLOCK, "LED Road Sign")
        tb.addBlockWithItem(BlockRegistry.COMPLEX_ROAD_SIGN_BLOCK, "Complex Road Sign")
        tb.addBlockWithItem(BlockRegistry.PEDESTRIAN_TRAFFIC_LIGHT_BLOCK, "Pedestrian Traffic Light")
        tb.addBlockWithItem(BlockRegistry.GUARD_RAIL_BLOCK, "Guardrail")
        tb.addBlockWithItem(BlockRegistry.SIDEWALK_CURB_BLOCK, "Sidewalk")
        tb.addBlockWithItem(BlockRegistry.TRAFFIC_CONE_BLOCK, "Traffic Cone")
        tb.addBlockWithItem(BlockRegistry.STREET_LAMP_BLOCK, "Street Lamp")
        tb.addBlockWithItem(BlockRegistry.BOLLARD_BLOCK, "Bollard")
        tb.addBlockWithItem(BlockRegistry.CONCRETE_BARRIER_BLOCK, "Concrete Barrier")

        // GUI
        tb.add("gui.dfroads.complex_sign_editor.add_element_label", "Add")
        tb.add("gui.dfroads.complex_sign_editor.background_picker_label", "Background")
        tb.add("gui.dfroads.complex_sign_editor.border_color_toggle_label", "Border color")
        tb.add("gui.dfroads.complex_sign_editor.color_picker_label", "Color")
        tb.add("gui.dfroads.complex_sign_editor.presets", "Presets")
        tb.add("gui.dfroads.complex_sign_editor.save_preset_hint", "Preset name")
        tb.add("gui.dfroads.facing.east_short", "E")
        tb.add("gui.dfroads.facing.north_short", "N")
        tb.add("gui.dfroads.facing.south_short", "S")
        tb.add("gui.dfroads.facing.west_short", "W")
        tb.add("gui.dfroads.generic.close", "Close")
        tb.add("gui.dfroads.road_painter.big_button_label", "Big Texture")
        tb.add("gui.dfroads.road_painter.change_color_button_label", "Change Color")
        tb.add("gui.dfroads.road_painter.change_texture_button_label", "Change Texture")
        tb.add("gui.dfroads.road_painter.change_texture_facing_button_label", "Change Texture Rotation")
        tb.add("gui.dfroads.road_painter.color_label", "Color")
        tb.add("gui.dfroads.road_painter.current_range_label", "Range: %d")
        tb.add("gui.dfroads.road_painter.interval_label", "Interval: %d")
        tb.add("gui.dfroads.road_painter.texture_facing_label", "Texture Facing")
        tb.add("gui.dfroads.road_painter.texture_label", "Texture")
        tb.add("gui.dfroads.road_painter.texture_preview_title", "Preview")
        tb.add("gui.dfroads.simple_sign_editor.texture_preview_title", "Preview")
        tb.add("gui.dfroads.simple_sign_editor.size_slider_label", "Size: %d")
        tb.add("gui.dfroads.traffic_light_editor.phases", "Phases")
        tb.add("gui.dfroads.traffic_light_editor.presets", "Presets")
        tb.add("gui.dfroads.traffic_light_editor.pulses", "Pulses")
        tb.add("gui.dfroads.traffic_light_editor.save_preset_hint", "Preset name")

        tb.add("gui.dfroads.road_painter.textures.road_empty", "Empty")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_s", "Arrow Straight")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_l", "Arrow Left")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_r", "Arrow Right")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_sl", "Arrow Straight Left")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_sr", "Arrow Straight Right")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_rl", "Arrow Right Left")
        tb.add("gui.dfroads.road_painter.textures.road_arrow_srl", "Arrow Straight Right Left")
        tb.add("gui.dfroads.road_painter.textures.road_bus", "Road Bus")
        tb.add("gui.dfroads.road_painter.textures.road_taxi", "Road Taxi")
        tb.add("gui.dfroads.road_painter.textures.road_parking", "Road Parking")
        tb.add("gui.dfroads.road_painter.textures.road_disabled_parking", "Road Disabled Parking")
        tb.add("gui.dfroads.road_painter.textures.road_crosswalk", "Crosswalk")
        tb.add("gui.dfroads.road_painter.textures.road_line_single", "Line Single")
        tb.add("gui.dfroads.road_painter.textures.road_line_diagonal", "Line Diagonal")
        tb.add("gui.dfroads.road_painter.textures.road_line_both", "Line Both")
        tb.add("gui.dfroads.road_painter.textures.road_line_merge", "Line Merge")
        tb.add("gui.dfroads.road_painter.textures.road_line_double", "Line Double")
        tb.add("gui.dfroads.road_painter.textures.road_line_double_diagonal", "Line Double Diagonal")
        tb.add("gui.dfroads.road_painter.textures.road_line_half_right", "Line Half Right")
        tb.add("gui.dfroads.road_painter.textures.road_line_half_left", "Line Half Left")
        tb.add("gui.dfroads.road_painter.textures.road_line_half_right_diagonal", "Line Half Right Diagonal")
        tb.add("gui.dfroads.road_painter.textures.road_line_half_left_diagonal", "Line Half Left Diagonal")
        tb.add("gui.dfroads.road_painter.textures.road_white", "White")
        tb.add("gui.dfroads.road_painter.textures.road_white_half", "White Half")
        tb.add("gui.dfroads.road_painter.textures.road_white_quarter", "White Quarter")

        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_10", "Speed 10")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_20", "Speed 20")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_30", "Speed 30")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_40", "Speed 40")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_50", "Speed 50")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_60", "Speed 60")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_70", "Speed 70")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_80", "Speed 80")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_90", "Speed 90")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_100", "Speed 100")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_110", "Speed 110")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_120", "Speed 120")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_10_end", "Speed 10 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_20_end", "Speed 20 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_30_end", "Speed 30 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_40_end", "Speed 40 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_50_end", "Speed 50 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_60_end", "Speed 60 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_70_end", "Speed 70 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_80_end", "Speed 80 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_90_end", "Speed 90 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_100_end", "Speed 100 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_110_end", "Speed 110 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_speed_120_end", "Speed 120 End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_generic_end", "Speed / No Overtaking End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_armadillo", "Warning Armadillo")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_axolotl", "Warning Axolotl")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_bend_left", "Warning Bend Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_bend_right", "Warning Bend Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_camel", "Warning Camel")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_cat", "Warning Cat")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_chicken_jockey", "Warning Chicken Jockey")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_chicken", "Warning Chicken")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_cow", "Warning Cow")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_creaking", "Warning Creaking")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_creeper", "Warning Creeper")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_crossing", "Warning Crossing")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_ender_dragon", "Warning Ender Dragon")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_firefly", "Warning Firefly")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_forg", "Warning Forg")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_goat", "Warning Goat")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_happy_ghast", "Warning Happy Ghast")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_horse", "Warning Horse")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_minecart", "Warning Minecart")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_narrows_both", "Warning Narrows Both")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_narrows_left", "Warning Narrows Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_narrows_right", "Warning Narrows Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_oncoming_traffic", "Warning Oncoming Traffic")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_other", "Warning Other")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_panda", "Warning Panda")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_phantom", "Warning Phantom")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_pig", "Warning Pig")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_priority_crossing", "Warning Priority Crossing")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_rabbit", "Warning Rabbit")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_railway_crossing", "Warning Railway Crossing")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_roadworks", "Warning Roadworks")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_s_bend_left", "Warning S Bend Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_s_bend_right", "Warning S Bend Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_school_children", "Warning School Children")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_sheep", "Warning Sheep")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_skeleton", "Warning Skeleton")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_slime", "Warning Slime")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_slippery", "Warning Slippery")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_slope_down", "Warning Slope Down")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_slope_up", "Warning Slope Up")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_sniffer", "Warning Sniffer")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_squareabout", "Warning Squareabout")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_traffic_light", "Warning Traffic Light")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_turtle", "Warning Turtle")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_uneven", "Warning Uneven")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_villager_crossing_road", "Warning Villager Crossing Road")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_warden", "Warning Warden")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_wither", "Warning Wither")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_warn_zombie", "Warning Zombie")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_keep_right", "Keep Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_keep_left", "Keep Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_right", "Only Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_left", "Only Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_left_and_right", "Only Left And Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_right_turn", "Only Right Turn")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_right_turn_and_straight", "Only Right Turn And Straight")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_left_turn", "Only Left Turn")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_left_turn_and_straight", "Only Left Turn And Straight")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_only_straight", "Only Straight")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_stop", "Stop")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_entry", "No Entry")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_give_way", "Give Way")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_priority_road", "Priority Road")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_priority_road_end", "Priority Road End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_highway", "Highway")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_highway_end", "Highway End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_motorway", "Motorway")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_motorway_end", "Motorway End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_one_way_left", "One Way Left")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_one_way_right", "One Way Right")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_parking", "Parking")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_oncoming_gives_way", "Oncoming Gives Way")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_give_way_to_oncoming", "Give Way To Oncoming")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_overtaking", "No Overtaking")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_overtaking_end", "No Overtaking End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_overtaking_for_trucks", "No Overtaking For Trucks")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_overtaking_for_trucks_end", "No Overtaking For Trucks End")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_left_turn", "No Left Turn")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_right_turn", "No Right Turn")
        tb.add("gui.dfroads.simple_sign_editor.textures.sign_no_u_turn", "No U Turn")

        tb.add("itemGroup.dfroads", "DFRoads")

        tb.add(ItemRegistry.ROAD_PAINTER, "Road Painter")

        try {
            val existingFilePath = dataOutput.modContainer.findPath("assets/${dataOutput.modId}/lang/en_us.json").get()
            tb.add(existingFilePath)
        } catch (e: Exception) {
            println("No existing en_us.json found")
        }
    }
}