@file:Suppress("unused", "unused")

package at.derfl007.dfroads

object Constants {
    val iconTextures = listOf(
        "icon_highway",
        "icon_car",
        "icon_center"
    )

    val roadTextures = listOf(
        "block/road_empty",
        "block/road_arrow_s",
        "block/road_arrow_l",
        "block/road_arrow_r",
        "block/road_arrow_sl",
        "block/road_arrow_sr",
        "block/road_arrow_rl",
        "block/road_arrow_srl",
        "block/road_crosswalk",
        "block/road_line_single",
        "block/road_line_merge",
        "block/road_line_double",
        "block/road_line_double_inner",
        "block/road_line_double_inner",
        "block/road_line_double_outer",
        "block/road_line_double_outer",
        "block/road_line_half_double",
        "block/road_line_half_double_inner",
        "block/road_line_half_double_outer",
        "block/road_line_split_right",
        "block/road_line_split_left",
        "block/road_line_diagonal",
        "block/road_white",
        "block/road_white_half",
        "block/road_white_quarter",
    )

    data class SignTextConfig(val x: Float, val y: Float, val width: Float, val height: Float)

    val signConfigs = mapOf<String, SignTextConfig?>(
        "block/sign_speed_10" to null,
        "block/sign_speed_20" to null,
        "block/sign_speed_30" to null,
        "block/sign_speed_40" to null,
        "block/sign_speed_50" to null,
        "block/sign_speed_60" to null,
        "block/sign_speed_70" to null,
        "block/sign_speed_80" to null,
        "block/sign_speed_90" to null,
        "block/sign_speed_100" to null,
        "block/sign_speed_110" to null,
        "block/sign_speed_120" to null,
        "block/sign_speed_10_end" to null,
        "block/sign_speed_20_end" to null,
        "block/sign_speed_30_end" to null,
        "block/sign_speed_40_end" to null,
        "block/sign_speed_50_end" to null,
        "block/sign_speed_60_end" to null,
        "block/sign_speed_70_end" to null,
        "block/sign_speed_80_end" to null,
        "block/sign_speed_90_end" to null,
        "block/sign_speed_100_end" to null,
        "block/sign_speed_110_end" to null,
        "block/sign_speed_120_end" to null,
        "block/sign_warn_armadillo" to null,
        "block/sign_warn_axolotl" to null,
        "block/sign_warn_bend_left" to null,
        "block/sign_warn_bend_right" to null,
        "block/sign_warn_camel" to null,
        "block/sign_warn_cat" to null,
        "block/sign_warn_chicken_jockey" to null,
        "block/sign_warn_chicken" to null,
        "block/sign_warn_cow" to null,
        "block/sign_warn_creaking" to null,
        "block/sign_warn_creeper" to null,
        "block/sign_warn_crossing" to null,
        "block/sign_warn_ender_dragon" to null,
        "block/sign_warn_firefly" to null,
        "block/sign_warn_forg" to null,
        "block/sign_warn_goat" to null,
        "block/sign_warn_happy_ghast" to null,
        "block/sign_warn_horse" to null,
        "block/sign_warn_minecart" to null,
        "block/sign_warn_narrows_both" to null,
        "block/sign_warn_narrows_left" to null,
        "block/sign_warn_narrows_right" to null,
        "block/sign_warn_oncoming_traffic" to null,
        "block/sign_warn_other" to null,
        "block/sign_warn_panda" to null,
        "block/sign_warn_phantom" to null,
        "block/sign_warn_pig" to null,
        "block/sign_warn_priority_crossing" to null,
        "block/sign_warn_rabbit" to null,
        "block/sign_warn_railway_crossing" to null,
        "block/sign_warn_roadworks" to null,
        "block/sign_warn_s_bend_left" to null,
        "block/sign_warn_s_bend_right" to null,
        "block/sign_warn_school_children" to null,
        "block/sign_warn_sheep" to null,
        "block/sign_warn_skeleton" to null,
        "block/sign_warn_slime" to null,
        "block/sign_warn_slippery" to null,
        "block/sign_warn_slope_down" to null,
        "block/sign_warn_slope_up" to null,
        "block/sign_warn_sniffer" to null,
        "block/sign_warn_squareabout" to null,
        "block/sign_warn_traffic_light" to null,
        "block/sign_warn_turtle" to null,
        "block/sign_warn_uneven" to null,
        "block/sign_warn_villager_crossing_road" to null,
        "block/sign_warn_warden" to null,
        "block/sign_warn_wither" to null,
        "block/sign_warn_zombie" to null,
        "block/sign_keep_right" to null,
        "block/sign_keep_left" to null,
        "block/sign_only_right" to null,
        "block/sign_only_left" to null,
        "block/sign_only_left_and_right" to null,
        "block/sign_only_right_turn" to null,
        "block/sign_only_right_turn_and_straight" to null,
        "block/sign_only_left_turn" to null,
        "block/sign_only_left_turn_and_straight" to null,
        "block/sign_only_straight" to null,
        "block/sign_stop" to null,
        "block/sign_no_entry" to null,
        "block/sign_give_way" to null,
        "block/sign_priority_road" to null,
        "block/sign_priority_road_end" to null,
        "block/sign_highway" to null,
        "block/sign_highway_end" to null,
        "block/sign_motorway" to null,
        "block/sign_motorway_end" to null,
        "block/sign_one_way_left" to null,
        "block/sign_one_way_right" to null,
        "block/sign_parking" to null,
        "block/sign_oncoming_gives_way" to null,
        "block/sign_give_way_to_oncoming" to null,
        "block/sign_no_overtaking" to null,
        "block/sign_no_overtaking_end" to null,
        "block/sign_no_overtaking_for_trucks" to null,
        "block/sign_no_overtaking_for_trucks_end" to null,
        "block/sign_no_left_turn" to null,
        "block/sign_no_right_turn" to null,
        "block/sign_no_u_turn" to null,
    )

    val signTextures = signConfigs.keys.toList()

    val complexSignTextures = listOf(
        "road_sign_complex_white",
        "road_sign_complex_blue",
        "road_sign_complex_green",
        "road_sign_complex_blue_arrow_r",
        "road_sign_complex_blue_arrow_l",
        "road_sign_complex_white_arrow_r",
        "road_sign_complex_white_arrow_l",
        "road_sign_complex_green_arrow_r",
        "road_sign_complex_green_arrow_l",
    )
}